name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

    # Activer Corepack pour accelerer l'installation de pnpm
      - name: Enable Corepack
        run: corepack enable

    # Installer version pnpm
      - name: Install pnpm
        run: corepack prepare pnpm@latest --activate

      # ---------- BACKEND ----------
      - name: Install backend deps
        working-directory: ./backend
        run: npm install

      - name: Build backend
        working-directory: ./backend
        run: npm run build

      # ---------- FRONTEND ----------
      - name: Install frontend deps
        working-directory: ./frontend
        run: pnpm install --frozen-lockfile # Utiliser --frozen-lockfile pour s'assurer que le lockfile est respecté

      - name: Build frontend
        working-directory: ./frontend
        run: pnpm run build

      # ---------- DOCKER BUILD TEST ----------
    #   - name: Build Docker backend
    #     run: docker build -t ai-backend ./backend